### ISSUE TITLE
no cpu&gpu active after new install

### ISSUE THREAD

**Issue by prekucki** [golemfactory/ya-provider-winui#104]

**Comment by ederenn** [comment]
in build https://github.com/golemfactory/ya-provider-winui/releases/tag/v0.2.1 
both indicators are disabled after first installation (clean one). It is possible to enable them and start mining

**Comment by warburg-pb** [comment]
can you try newer release eg: https://github.com/golemfactory/ya-provider-winui/releases/tag/v0.2.4 

(AFAIK it was fixed in 0.2.2)

**Comment by ederenn** [comment]
working in v0.2.4
