### ISSUE TITLE
different estimated profit units on different cards

### ISSUE THREAD

**Issue by ederenn** [golemfactory/ya-provider-winui#127]
on dashboard profit is shown per month
in wallet per day. Both should be showing per month

![per month](https://user-images.githubusercontent.com/32061891/129727918-2959df50-2bda-47db-9617-4ad9b281dbdf.PNG)

![perday](https://user-images.githubusercontent.com/32061891/129727887-5a99d8af-ae3f-4e1e-8d93-435a2429ac91.PNG)

**Comment by warburg-pb** [comment]
should be fixed in 2.5
