### ISSUE TITLE
opacity slider is showing wrong percentage after instalation

### ISSUE THREAD

**Issue by ederenn** [golemfactory/ya-provider-winui#129]
slider is set on 0, when opacity is set around 80%, 
ver 0.2.4

![opacity](https://user-images.githubusercontent.com/32061891/129739494-fdaea48b-ddf3-4515-aab4-6be76b843c92.PNG)

**Comment by warburg-pb** [comment]
fixed in https://github.com/golemfactory/ya-provider-winui/pull/131

v 0.2.5 candidate
