### ISSUE TITLE
mining switches are not working

### ISSUE THREAD

**Issue by ederenn** [golemfactory/ya-provider-winui#14]
operating system:Windows 10 pro
graphic card: GeForce RTX 2070

1) In setup app detects graphic card, but later on it seems not enabled in dashboard.  

2) Switch is switched off and in description it is stated - `gpu cards enabled`. Description is confusing.

3) I am not able to start mining - EthDrcMiner64.exe is not appearing in Task Manager, although I am able to click button `Start Minning` and it changes to 'Stop Mining`

 1.
![Capture27-07-1](https://user-images.githubusercontent.com/32061891/127154035-26a4d7e8-ddff-49df-84c5-9995ff196e89.PNG)

 2.
![Capture27-07-2](https://user-images.githubusercontent.com/32061891/127155093-b98361ea-57d1-4831-93a2-069d598d1f46.PNG)

 3.
![cos nie dziala](https://user-images.githubusercontent.com/32061891/127155107-9f5f97f3-32ca-493b-8e3d-7fc52d6604a4.PNG)

**Comment by prekucki** [comment]
fixed in 
https://github.com/golemfactory/ya-provider-winui/releases/download/v0.1.2/GolemUISetup.msi

**Comment by ederenn** [comment]
in build https://github.com/golemfactory/ya-provider-winui/releases/tag/v0.1.2 
switches are working, it is possible to start mining
