### ISSUE TITLE
Miner keeps getting stuck on "ready to mine"

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/ya-provider-winui#178]
Discord user Potatoman#9319 [reports](https://discord.com/channels/684703559954333727/877848913753821225/884003026900254730) that his antivirus continues to put the miner into quarantine on his system. He has now added it to his antivirus exceptions and reinstalled the miner, but it keeps on getting stuck on "**ready to mine**"

[Discord user TiaxtheGrand#9255 reports the same issue](https://discord.com/channels/684703559954333727/877848913753821225/884134387233464400)

[Discord user Labina_Masters#9585 reports his app says "**Ready to Mine**" also and his antivirus has **not** blocked anything.](https://discord.com/channels/684703559954333727/877848913753821225/884134494842527775)

**Comment by prekucki** [comment]
@cryptobench requestor was stopped yesterday during move to new server.

at 05-09-2021 requestor node was broken and did not send mining jobs
