### ISSUE TITLE
A task was cancelled notification spam

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/ya-provider-winui#179]
[Tester r4x on Discord reports a bunch of notification spam ](https://discord.com/channels/684703559954333727/877848746036191282/883765223390052413)

![image](https://user-images.githubusercontent.com/33448819/132226460-6ec9e087-3694-42fc-a303-b961ff908e41.png)

**Comment by warburg-pb** [comment]
resolved in https://github.com/golemfactory/ya-provider-winui/pull/182 
(commented out messagebox with unexpected error, error still can be found in log files)
