### ISSUE TITLE
Invisible button that takes you to Golems website

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/ya-provider-winui#180]
SpM_R3[SIST]#0100 [reports](https://discord.com/channels/684703559954333727/877848913753821225/883367354011095150) that there's an invisible button under the Node Name section, and if you hover your mouse and right click, you'll be directed to the website.

![image](https://user-images.githubusercontent.com/33448819/132228046-c8e38609-9de2-4ab3-a7f0-c3ec17ede673.png)

**Comment by warburg-pb** [comment]
we will add appropriate texture soon
