### ISSUE TITLE
Closing UI closes only interface, app is still working in tray

### ISSUE THREAD

**Issue by ederenn** [golemfactory/ya-provider-winui#28]
operating system:Windows 10 pro
graphic card: GeForce RTX 2070
Golem Miner v0.1.2 2c81f93

Closing UI with cross, closes only interface, app is still working in tray
To shut the app down completety user needs to check tray and close it there. This is confusing, it's easy to miss that it is still working.

**Comment by warburg-pb** [comment]
![image](https://user-images.githubusercontent.com/22456155/128052051-0ed476a1-175a-49f7-95e1-339653550afd.png)

this behavior now can be adjusted in advanced settings, introduced in commit:
https://github.com/golemfactory/ya-provider-winui/commit/bd85c8949ee3a48220e48ebad94c4105f90f7018

If still confusing we can introduce additional notification:
![image](https://user-images.githubusercontent.com/22456155/128052567-b02a3aef-d1bb-4251-84de-774c3d869bee.png)

**Comment by warburg-pb** [comment]
solution proposal introduced in pull request https://github.com/golemfactory/ya-provider-winui/pull/57

![image](https://user-images.githubusercontent.com/22456155/128057751-f8df2c5d-5c56-4d2b-8095-12a6b423b013.png)

**Comment by warburg-pb** [comment]
resolved in https://github.com/golemfactory/ya-provider-winui/commit/c378fc288f9fa5917640c4993310f2f196699cd2
