### ISSUE TITLE
Confusing description mining switches

### ISSUE THREAD

**Issue by ederenn** [golemfactory/ya-provider-winui#29]
operating system:Windows 10 pro
graphic card: GeForce RTX 2070
Golem Miner v0.1.2 2c81f93

Switches are switched on but description shows "idle". This is not intuitive.

![Capture-29-07](https://user-images.githubusercontent.com/32061891/127519893-f6cbab13-d067-4b8a-a6ba-911d8f7d1c21.PNG)

**Comment by warburg-pb** [comment]
will be changed according to spec:

https://www.notion.so/golemnetwork/43f3feeb8a0348b7bf7f27dc263ea489?v=4f4b7d16bede480da88fd91cb9f2644d&p=31724811c18e4bf1befa3a990a1255b1

**Comment by warburg-pb** [comment]
changed in https://github.com/golemfactory/ya-provider-winui/commit/cd0cd709f6b76691cbbe3eb85a98023559757600
