### ISSUE TITLE
Clicking on "Got them all" button quickly when confirming seed phrase closes the app 

### ISSUE THREAD

**Issue by ederenn** [golemfactory/ya-provider-winui#31]
operating system:Windows 10 pro
graphic card: GeForce RTX 2070
Golem Miner pre-rel-v0.7.3-rc1  f1f6e47

Clicking on "Got them all" button quickly when confirming seed phrase closes the app. Checked on expert path, create new wallet. 
To reproduce it, choose create new wallet, follow the flow until step 2 "Seed phrase" and click quickly two or three times on "Got them all" button. Whole app will shut down completely.

![got](https://user-images.githubusercontent.com/32061891/127527592-d61d32c5-abf4-4f4a-ac3c-aa0b64e26de2.PNG)

**Comment by warburg-pb** [comment]
fix awaiting in pull request https://github.com/golemfactory/ya-provider-winui/pull/56

**Comment by warburg-pb** [comment]
fixed in https://github.com/golemfactory/ya-provider-winui/commit/b9a1f4cf954bbb24ae917b809c82e626acd0cbbc
