### ISSUE TITLE
App should inform that running benchmark stops current mining

### ISSUE THREAD

**Issue by ederenn** [golemfactory/ya-provider-winui#46]
operating system:Windows 10 pro
graphic card: GeForce RTX 2070
Golem Miner v0.1.4  4f7fd4b

App should inform that running benchmark stops current mining. Alternatively running benchmark when node is mining, should be disabled.  

After running benchmark when miner is on, interface is showing as app is still mining, although mining processes are stopped/
![stop](https://user-images.githubusercontent.com/32061891/127892924-52933ac4-1a96-47b5-9b2c-773896cf5f01.PNG)

**Comment by warburg-pb** [comment]
As discussed with design / dev team ModalDialog will be introduced to ask user if he want to stop mining operation to perform benchmark

**Comment by warburg-pb** [comment]
work in progress:

![image](https://user-images.githubusercontent.com/22456155/128710871-8c096daa-29ad-4cdd-adf4-80c7ddaadca4.png)

**Comment by warburg-pb** [comment]
solved in https://github.com/golemfactory/ya-provider-winui/commit/fee8b155b081f77bd8772ab8191f0644ab766f9d
