### ISSUE TITLE
I tried build #16 the card seems good to be mining but is idle

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/ya-provider-winui#49]
plus -> `ready to mine` next to `stop mining` sounds weird
the screanshots: 
![miner-idle-geforce-gtx-1070](https://user-images.githubusercontent.com/5002408/127993891-74a4b808-34f9-4267-8776-41711e79e045.png)

![miner-ready-but-idle-geforce-gtx-1070](https://user-images.githubusercontent.com/5002408/127994176-3a0f99d9-ebae-4874-80fa-02ed6bc73beb.png)

**Comment by warburg-pb** [comment]
GPU mining should be enabled to mine 
![image](https://user-images.githubusercontent.com/22456155/128064336-5d4da30b-db15-4ccd-a957-e66860ffe7e5.png)

today requestor app was turned off so maybe that's the reason why app was not mining even with beforementioned switch turned on

test should be repeated once requestor app is running again  ( @prekucki )

**Comment by mateuszsrebrny** [comment]
I tried clicking on the red toggle, nothing happened.
Today I have installed (without cleaning dirs) `#22` and it looked the same (meaining the card toggle was red and it didn't react to me trying to enable it)
Together with Reqc I cleared the directories and now it is better.

@prekucki asked me to upload the data dirs which somehow contain info that my benchmark didn't work :)
Here: 
[ThorgMiner-ya-provider-20210810.zip](https://github.com/golemfactory/ya-provider-winui/files/6961070/ThorgMiner-ya-provider-20210810.zip)
