### ISSUE TITLE
`cryoto` typo in one of the welcome screens

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/ya-provider-winui#50]
Probably in the description of `expert` setup mode

**Comment by warburg-pb** [comment]
fixed in https://github.com/golemfactory/ya-provider-winui/commit/4bdf4bf3232c251aeeb527f4895eea44cc907112

**Comment by warburg-pb** [comment]
another typo fix,
awaiting merge in pull request https://github.com/golemfactory/ya-provider-winui/pull/55

**Comment by warburg-pb** [comment]
fixed in https://github.com/golemfactory/ya-provider-winui/commit/286e894bf613d0108c8421675d0f24daa6c10788
