### ISSUE TITLE
change wording "ADVANCED" on Dashboard in CPU/GPU mining

### ISSUE THREAD

**Issue by ederenn** [golemfactory/ya-provider-winui#70]
![advanced](https://user-images.githubusercontent.com/32061891/128531244-222aa9a2-c89b-4db9-afe5-ca8a8723b76e.PNG)
this button is simply redirecting to settings tab (not the advanced settings)

**Comment by warburg-pb** [comment]
will be changed to "SETTINGS"

**Comment by warburg-pb** [comment]
changed in https://github.com/golemfactory/ya-provider-winui/commit/03873326101eca63cc8199f0f262b41b7b9d46f2
